### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by northboys** [dewanakl/undangan-api#1]
Hi Mas, need a guide for deploy..🙏

**Comment by dewanakl** [comment]
sebelumnya saya minta maaf karena belum sempat membikin dokumentasinya, saya akan membuat di readme.md di repo ini saja ya mas, tunggu besok atau lusa ya mas, terima kasih

**Comment by northboys** [comment]
Okay Mas, terima kasih ya 🙏

**Comment by dewanakl** [comment]
Sudah saya tuliskan mas 🙏

**Comment by dewanakl** [comment]
@northboys

**Comment by dewanakl** [comment]
@northboys 

https://github.com/dewanakl/undangan-api/issues/2

semoga bisa membantu juga mas

**Comment by northboys** [comment]
terima kasih Mas, bisa di-close untuk issue-nya ya 🙏
