### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by thatxxuc** [dewanakl/undangan-api#12]
Maaf mas mau tanya, apinya udah berhasil dideploy ke vercel, cuman pas get api session itu kena cors

![image](https://github.com/dewanakl/undangan-api/assets/39077603/36721374-fd99-4f3b-90f5-fe9f3c79c24e)

terus response code nya sih 200, tapi ada error ini diresponse bodynya

`<br />
<b>Fatal error</b>:  Uncaught Exception: Error could not save log file in /var/task/user/vendor/kamu/framework/src/Core/Support/Error.php:190
Stack trace:
#0 /var/task/user/vendor/kamu/framework/src/Core/Facades/Web.php(211): Core\Support\Error-&gt;report()
#1 /var/task/user/vendor/kamu/framework/src/Core/Facades/Web.php(245): Core\Facades\Web-&gt;handleError(Object(Exception))
#2 /var/task/user/public/index.php(22): Core\Facades\Web-&gt;run()
#3 /var/task/user/api/index.php(9): require_once('/var/task/user/...')
#4 {main}
  thrown in <b>/var/task/user/vendor/kamu/framework/src/Core/Support/Error.php</b> on line <b>190</b><br />
` 

Mohon bantuannya terima kasih

**Comment by thatxxuc** [comment]
ternyata password db yg dimasukin salah. 

Makasih mas

**Comment by dewanakl** [comment]
Owh, sama sama mas
