### ISSUE TITLE
Responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec (LOCALHOST)

### ISSUE THREAD

**Issue by madmouse17** [dewanakl/undangan-api#16]
ini saat saya coba di **LOCALHOST** mengalami masalah error seperti digambar saat load module.

![image](https://github.com/dewanakl/undangan-api/assets/33163281/5d78b8f9-8e24-40f1-9035-b88e628e7949)

**Comment by dewanakl** [comment]
Untuk versi ini, tepatnya pada sisi front end menggunakan module dan dari sisi browser perlu mime type yang tepat
sehingga perlu server seperti ekstensi live server pada vscode untuk menjalankannya, terima kasih
