### ISSUE TITLE
key panjang maxsimal: 50

### ISSUE THREAD

**Issue by blackstar-git** [dewanakl/undangan-api#17]
https://jam.dev/c/cf84510a-7a80-4d9a-aa08-f67041e8833c
Muncul notif key panjang maxsimal: 50 seperti pada video di atas

![image](https://github.com/dewanakl/undangan-api/assets/56350314/d49bd1f1-d563-4282-b417-78305b5ff4e3)
![image](https://github.com/dewanakl/undangan-api/assets/56350314/9fb7d5e4-8b03-428b-aa69-bcda17717218)
![image](https://github.com/dewanakl/undangan-api/assets/56350314/b3c9e3dc-c153-4ba6-8df7-dfe0af908da2)

**Comment by dewanakl** [comment]
Untuk api key bisa di ambil dari dashboard kemudian pengaturan mas

**Comment by blackstar-git** [comment]
done, problem ketemu mas, gak baaca code dengan cermat wkwk
terimakasih banyak, sangat membantu
