### ISSUE TITLE
help me :

### ISSUE THREAD

**Issue by superuser-99** [dewanakl/undangan-api#2]
hallo mas, saya mau belajar bagian _backend API_ ini barangkali bisa ngasih tutor 🙏
terima kasih mas. @dewanakl

**Comment by dewanakl** [comment]
bisa mas, ada kendala dimana masnya ?🙏

**Comment by superuser-99** [comment]
di bagian ucapan dan do'a mas, 
itu bagaimana caranya supaya dari awal lagi ya.. 🙏
![image](https://user-images.githubusercontent.com/114789899/230760946-eb94874d-da6e-4af0-8a8c-6af112f9db9c.png)

**Comment by superuser-99** [comment]
> di bagian ucapan dan do'a mas, itu bagaimana caranya supaya dari awal lagi ya.. 🙏 ![image](https://user-images.githubusercontent.com/114789899/230760946-eb94874d-da6e-4af0-8a8c-6af112f9db9c.png)

banyak history padahal di localhost

**Comment by superuser-99** [comment]
> bisa mas, ada kendala dimana masnya ?🙏

cara bikin nya dimana dan bagaimana mas

**Comment by dewanakl** [comment]
maaf mas, yang dimaksud dari awal itu apa ya mas?🙏

**Comment by superuser-99** [comment]
jadi history nya mas

**Comment by superuser-99** [comment]
bagian ini saya tidak faham, maap mas 🙏🏻
saya baru pertama main2 code

![7991046B-F699-4A02-B30E-78620FDE293E](https://user-images.githubusercontent.com/114789899/230762835-3aca5e29-fc5e-4e20-8fb7-d2d56f13bf57.png)

**Comment by dewanakl** [comment]
owh, kalau itu nggak bisa di reset mas

jadi masnya perlu bikin semacam api server sendiri untuk undangan mas nya sendiri mas

**Comment by dewanakl** [comment]
> bagian ini saya tidak faham, maap mas 🙏🏻 saya baru pertama main2 code
> 
> ![7991046B-F699-4A02-B30E-78620FDE293E](https://user-images.githubusercontent.com/114789899/230762835-3aca5e29-fc5e-4e20-8fb7-d2d56f13bf57.png)

untuk ini langkah langkah deploy di vercel mas

**Comment by superuser-99** [comment]
caranya bagimana mas 🙏🏻 
saya sudah coba tapi tidak bisa. 

barangkali bisa dibuat video record nya,
terima kasih mas.

**Comment by dewanakl** [comment]
bisa mas, besok atau lusa saya coba bikin ya mas, nanti saya kabari lewat comment issues ini

**Comment by superuser-99** [comment]
makasih banyak mas.

**Comment by dewanakl** [comment]
siap mas, sama sama

**Comment by dewanakl** [comment]
atau masnya ada hosting?

**Comment by superuser-99** [comment]
> atau masnya ada hosting?

Ada mas.

**Comment by dewanakl** [comment]
bisa langsung hosting saja mas, karena kalau pake vercel untuk uji coba saja mas

**Comment by superuser-99** [comment]
tutorialnya mas 🙏🏻

**Comment by dewanakl** [comment]
https://youtu.be/WOVyAw1UAtI

**Comment by dewanakl** [comment]
Semoga bisa membantu mas
🙏🏻

**Comment by superuser-99** [comment]
> php 8.1 juga mas

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

di laman web ada pesan gitu mas. 🙏🏻

**Comment by dewanakl** [comment]
cek php nya coba mas

php -v

minimal php 8.1.xx mas

**Comment by superuser-99** [comment]
> cek php nya coba mas
> 
> php -v
> 
> minimal php 8.1.xx mas

![image](https://user-images.githubusercontent.com/114789899/231133947-6d967680-69a3-4d0d-974c-a02706a66ab4.png)

udah ini mas

**Comment by dewanakl** [comment]
Kalau di terminalnya gimana mas?

**Comment by superuser-99** [comment]
> Kalau di terminalnya gimana mas?

![image](https://user-images.githubusercontent.com/114789899/231135048-21659b9e-373a-4cd0-b3b8-db60fc87e8ee.png)

ini mas..

**Comment by dewanakl** [comment]
sudah bisa itu mas

**Comment by superuser-99** [comment]
> sudah bisa itu mas

![D59B890E-11BA-475A-823E-8D6EA39FF823](https://user-images.githubusercontent.com/114789899/231180577-030e269a-fecb-44ce-987d-72db4ca0e1e9.png)


masih gini duh repot 🫠

**Comment by dewanakl** [comment]
owalah, ini berarti di hostingnya mas

**Comment by superuser-99** [comment]
> owalah, ini berarti di hostingnya mas

alur yang saya buat gini mas, saya coba cerita ya. 

jadi saya buat subdomain kan yang 1. domain : backend.millah-hanif.site dengan nama folder = sandbox

yang ke 2. bikin lagi domain : file.milah-hanif.site dengan nama folder = sandboxfile

barangkali begitu mas, koreksi nya gatau benar atau salah 🙏🏻

namun ada perbedaan dengan hosting di video mas, kalo di hosting saya kebetulan pakai niagahoster semua folder+file nya ada di public_html tidak ada yang diluar.

**Comment by superuser-99** [comment]
> Owalah mas, tetapi sudah support php 8.1 kan mas?

atau setting php di hosting nya juga harus 8.1.xx  mas?

**Comment by superuser-99** [comment]
> > owalah, ini berarti di hostingnya mas
> 
> alur yang saya buat gini mas, saya coba cerita ya.
> 
> jadi saya buat subdomain kan yang 1. domain : backend.millah-hanif.site dengan nama folder = sandbox
> 
> yang ke 2. bikin lagi domain : file.milah-hanif.site dengan nama folder = sandboxfile
> 
> barangkali begitu mas, koreksi nya gatau benar atau salah 🙏🏻
> 
> namun ada perbedaan dengan hosting di video mas, kalo di hosting saya kebetulan pakai niagahoster semua folder+file nya ada di public_html tidak ada yang diluar.

ini cara saya buat domain dan file tidak ada salah kan mas? 🙏🏻
atau bagaimana saya memang kurang faham.

**Comment by dewanakl** [comment]
betul mas 8.1xx

coba mas, bikin file php_info saja mas

**Comment by superuser-99** [comment]
> betul mas 8.1xx
> 
> coba mas, bikin file php_info saja mas

sudah mah tapi gak faham ini

**Comment by superuser-99** [comment]
> betul mas 8.1xx
> 
> coba mas, bikin file php_info saja mas

![image](https://user-images.githubusercontent.com/114789899/231224324-0f0525f3-210c-40bb-b6eb-7abf553623cd.png)

sudah berhasil mas, namun di tahapan migrasi ada error

**Comment by dewanakl** [comment]
php mysql extension sudah aktif di hostingnya mas?

**Comment by superuser-99** [comment]
> php mysql extension sudah aktif di hostingnya mas?

![396AB9A0-5D7B-468E-968C-CF655968BB1B](https://user-images.githubusercontent.com/114789899/231289363-96eaeb86-1496-4342-a25c-0a978c7d2d37.png)

sepertinya sudah aktif mas, saya gunakan setting default.

**Comment by superuser-99** [comment]
> ![image](https://user-images.githubusercontent.com/53048107/231328507-410da024-2d64-42c9-9c02-9e917a6946b7.png) ini coba mas

sudah seperti itu mas, 
tapi hasilnya masih spt ini : 
![image](https://user-images.githubusercontent.com/114789899/231331851-0e5eaaba-8ec1-4b0b-b06e-d5ef5883fe7f.png)

**Comment by superuser-99** [comment]
> > betul mas 8.1xx
> > coba mas, bikin file php_info saja mas
> 
> ![image](https://user-images.githubusercontent.com/114789899/231224324-0f0525f3-210c-40bb-b6eb-7abf553623cd.png)
> 
> sudah berhasil mas, namun di tahapan migrasi ada error

![image](https://user-images.githubusercontent.com/114789899/231333524-8e106a2e-c12c-40d7-9545-0c7110d5d24d.png)


barangkali koreksi  nya mas  🙏🏻

**Comment by dewanakl** [comment]
![image](https://user-images.githubusercontent.com/53048107/231338087-e68b4491-57ed-4d70-a28f-49e0dcec7e5d.png)
coba display error dulu mas

**Comment by superuser-99** [comment]
> ![image](https://user-images.githubusercontent.com/53048107/231338087-e68b4491-57ed-4d70-a28f-49e0dcec7e5d.png)
> coba display error dulu mas

sudah mas tapi masih sama

**Comment by superuser-99** [comment]
> > ![image](https://user-images.githubusercontent.com/53048107/231338087-e68b4491-57ed-4d70-a28f-49e0dcec7e5d.png)
> > coba display error dulu mas
> 
> sudah mas tapi masih sama

seperti ini 


![](https://user-images.githubusercontent.com/114789899/231331851-0e5eaaba-8ec1-4b0b-b06e-d5ef5883fe7f.png)

**Comment by superuser-99** [comment]
di bagian ini mungkin ada salah enggak ya mas?  🙏🏻

antara penyimpanan folder dan script nya. 

![](https://user-images.githubusercontent.com/114789899/231333524-8e106a2e-c12c-40d7-9545-0c7110d5d24d.png)

**Comment by dewanakl** [comment]
display error di checklist dulu coba mas

**Comment by superuser-99** [comment]
> display error di checklist dulu coba mas

sudah mas, masih tidak ada perbedaan

**Comment by dewanakl** [comment]
coba mas, cd ../sandboxfile saja mas

**Comment by superuser-99** [comment]
> 

pasrah mas, masih sama gada perubahan

**Comment by dewanakl** [comment]
coba google meet mas?

**Comment by dewanakl** [comment]
https://meet.google.com/iav-xhvq-eus

**Comment by superuser-99** [comment]
> 
monggo barangkali mas beresedia, 
ini akun cpanl nya 

https://millah-hanif.site/cpanel
usr : u1577422
pss : NB-Superteam100

nyerah mas, saya percaya mas nya ko  
gpp. 🙏🏻 

terima kasih mas.

**Comment by dewanakl** [comment]
![image](https://user-images.githubusercontent.com/53048107/231358245-50b0d610-9309-40c2-beea-bc8080310aac.png)
ini hapus saja mas, karena isi dari frameworknya

**Comment by superuser-99** [comment]
> ![image](https://user-images.githubusercontent.com/53048107/231358245-50b0d610-9309-40c2-beea-bc8080310aac.png)
> ini hapus saja mas, karena isi dari frameworknya

siap mas, terima kasih banyak. 
semoga kebaikan mah diganti dengan yang lebih2 😇

**Comment by dewanakl** [comment]
Aamiin mas 🙏

**Comment by dewanakl** [comment]
Sudah logout juga mas

**Comment by dewanakl** [comment]
Karena di niagahoster melarang fungsi execute system mas, seperti shell_exec, exec, dll

jadi tadi migrasi database secara manual lewat phpmyadmin tidak bisa karena passwordnya nggak tau mas

akhirnya migrasi lewat file php sendiri mas, agar membuat tabel di databasenya secara otomatis

**Comment by superuser-99** [comment]
![BCCCEAEF-F0E1-47C8-BB46-9E6A9EA9FF2C](https://user-images.githubusercontent.com/114789899/231362247-f1d5143d-7dab-4732-b542-10f219a50ce7.jpeg)

ini apalagi ya mas  😵‍💫

**Comment by dewanakl** [comment]
Di html sudah di ganti mas?

![image](https://user-images.githubusercontent.com/53048107/231363381-718dcb57-11b3-4526-9ba7-50aec700bf1c.png)
jadi seperti ini misalnya mas

**Comment by superuser-99** [comment]
> Di html sudah di ganti mas?
> 
> ![image](https://user-images.githubusercontent.com/53048107/231363381-718dcb57-11b3-4526-9ba7-50aec700bf1c.png) jadi seperti ini misalnya mas

jadi apa saya yang harus di ubah,
password nya itu tidak perlu diganti ya mas?

**Comment by dewanakl** [comment]
nggak perlu nggak masalah mas

**Comment by superuser-99** [comment]
> nggak perlu nggak masalah mas

SIAP
