### ISSUE TITLE
CORS iissue

### ISSUE THREAD

**Issue by shyntaayu** [dewanakl/undangan-api#22]
![issue-cors](https://github.com/user-attachments/assets/91c189c5-f3cd-46ec-882a-dc27606a1171)

mas tolong, ini fixingnya gimana
bisa post, tapi gak bisa get kena cors

**Comment by dewanakl** [comment]
pastikan lokasi deploy vercel dan db ada di singapura kak

**Comment by shyntaayu** [comment]
sudah solved mas, 
nambah headers di vercel.json

makasih solusinya
