### ISSUE TITLE
Izin tanya mas

### ISSUE THREAD

**Issue by deprito** [dewanakl/undangan-api#4]
Selamat malam Mas, saya sudah coba beberapa metode instalasi (vercel dan hosting)

https://undanganapi-d1bs.vercel.app/ - Error 503 / 500 saya tidak dapat mengecek bagian apa yang error dari vercel ini.. Tapi kalo saya embed pakai vercel-nya mas, aman2 saja...

Kira - kira kesalahannya apa ya mas? saya bingung utak atiknya

Sekali lagi, terima kasih ya mas

**Comment by deprito** [comment]
sudah bisa mas amaan

**Comment by dewanakl** [comment]
Maaf ya mas, agak terlambat respon nya, kalau sudah aman syukurlah mas.

Pada tanggal Sen, 10 Jul 2023 pukul 21.29 deprito ***@***.***>
menulis:
