### ISSUE TITLE
izin nanya mas 

### ISSUE THREAD

**Issue by gentafg11** [dewanakl/undangan-api#5]
cara dapatin app key dari mana ya mas,saya soalnya baru belajar

**Comment by dewanakl** [comment]
Dari "php saya key" mas

Pada tanggal Sab, 15 Jul 2023 03.12, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
oke mas,terima kasih sebelumnya,kalo error nya begini gimana ya mas?
![image](https://github.com/dewanakl/undangan-api/assets/139584534/4eb499c4-0637-414e-97dd-1774b23d95b0)

**Comment by dewanakl** [comment]
Kalau ini ubah env DEBUG menjadi false mas

Pada tanggal Sab, 15 Jul 2023 06.39, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
oke mas,trus saya mau nanya mas,cara nyambungin ke proyek undangan nya gimana mas?

**Comment by dewanakl** [comment]
Tinggal isikan url dari backend nya saja mas

Pada tanggal Sab, 15 Jul 2023 06.50, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
udah mas,dibagian head sama body doang kan mas?,tetap ga bisa mas

**Comment by dewanakl** [comment]
Coba ss saja mas

Pada tanggal Sab, 15 Jul 2023 08.09, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
udah dimasukin mas ,btw api nya ga perlu di apa apain lagi kan mas,kalau sudah jalan?
![image](https://github.com/dewanakl/undangan-api/assets/139584534/da42aff2-9af9-4154-ade3-4e095edcd7f7)

**Comment by gentafg11** [comment]
nah tapi kok masih ga bisa ya mas
![image](https://github.com/dewanakl/undangan-api/assets/139584534/42c8c86d-2c82-44a2-85e1-706e903cc114)

**Comment by dewanakl** [comment]
Inspek elemen coba mas

Pada tanggal Sab, 15 Jul 2023 08.21, gentafg11 ***@***.***>
menulis:

**Comment by dewanakl** [comment]
Link deployment pastikan udah betul ya mas

Pada tanggal Sab, 15 Jul 2023 08.22, Dewana Kretarta <
***@***.***> menulis:

**Comment by gentafg11** [comment]
![image](https://github.com/dewanakl/undangan-api/assets/139584534/cf0489dc-b1d5-4081-92a8-478880a1d556)

**Comment by gentafg11** [comment]
kalau begini sudah betul belum mas?
![image](https://github.com/dewanakl/undangan-api/assets/139584534/1736ca6d-fdd5-4644-9c5e-32c13d8f3af1)

**Comment by gentafg11** [comment]
![image](https://github.com/dewanakl/undangan-api/assets/139584534/de02fd5c-ffbb-4b2e-a4f5-507148335172)

**Comment by dewanakl** [comment]
Iya sudah betul mas

Pada tanggal Sab, 15 Jul 2023 08.26, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
gimana ya mas,api nya kalau sudah berhasil di deploy ga perlu di apa apain lagi kan mas?

**Comment by dewanakl** [comment]
Iya betul tinggal di coba aja mas

Pada tanggal Sab, 15 Jul 2023 08.38, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
oh iya mas,env JWT_KEY ga ada saya masukin mas,apa gara gara itu kali mas?

**Comment by gentafg11** [comment]
saya cek di log vercel nya begini mas
![image](https://github.com/dewanakl/undangan-api/assets/139584534/bec54a40-2505-4cd8-9506-3799cf55aeeb)

**Comment by dewanakl** [comment]
Database nya udah betul mas? Sama cek env lagi coba mas

Pada tanggal Sab, 15 Jul 2023 08.42, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
ini envi nya mas
![image](https://github.com/dewanakl/undangan-api/assets/139584534/72f08cb2-8475-44e6-8310-d82ce6a84b67)
![image](https://github.com/dewanakl/undangan-api/assets/139584534/028005f7-3d9d-44d6-80c4-744f0b9e8025)

**Comment by gentafg11** [comment]
ini database nya mas
![image](https://github.com/dewanakl/undangan-api/assets/139584534/1afedfb0-7424-421d-ada5-62b63598dd6d)

**Comment by dewanakl** [comment]
Coba redeploy lagi mas

Pada tanggal Sab, 15 Jul 2023 10.48, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
apa nya ni mas yang di redeploy

**Comment by gentafg11** [comment]
ini mas database nya
![image](https://github.com/dewanakl/undangan-api/assets/139584534/57ac65da-aeb3-4f27-b90f-b021e5cd97e3)

**Comment by dewanakl** [comment]
Belum migrasi mas, coba cek videonya mas

Pada tanggal Sab, 15 Jul 2023 11.04, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
video yang mana ya mas?

**Comment by gentafg11** [comment]
oh iya mas,itu short url dikit nya lagi error mas

**Comment by dewanakl** [comment]
Iya mas sekarang udah bisa mas

Pada tanggal Sab, 15 Jul 2023 11.13, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
sudah saya lihat video nya mas,trus pas step ini error mas
![image](https://github.com/dewanakl/undangan-api/assets/139584534/1cb700d6-90a4-4a9a-ab8b-8e3040bfccfb)

**Comment by dewanakl** [comment]
Kalau ini drivernya belum ada mas

Pada tanggal Sab, 15 Jul 2023 12.25, gentafg11 ***@***.***>
menulis:

**Comment by dewanakl** [comment]
Atau boleh gmeet mas

Pada tanggal Sab, 15 Jul 2023 12.39, Dewana Kretarta <
***@***.***> menulis:

**Comment by gentafg11** [comment]
boleh mas,tak siapkan ya atau masnya ada discord ndak

**Comment by gentafg11** [comment]
https://meet.google.com/pws-mibx-htx

**Comment by dewanakl** [comment]
Boleh discord mas

Pada tanggal Sab, 15 Jul 2023 12.40, gentafg11 ***@***.***>
menulis:

**Comment by gentafg11** [comment]
boleh kirim link discord nya mas  ?

**Comment by dewanakl** [comment]
username dc saya ini mas dkl8270

**Comment by gentafg11** [comment]
sudah mas nama dc ku grizzel#5980
