### ISSUE TITLE
Bearer token kosong

### ISSUE THREAD

**Issue by karuniawanekasakti** [dewanakl/undangan-api#8]
izin tanya mas, api udah saya deploy dan berhasil nampilin data, tapi seminggu kemudian malah erro bearer token kosong dan comment ga mau muncul. Kira kira kenapa ya mas mohon bantuannya

**Comment by dewanakl** [comment]
Kemungkinan besar ada pada frontend dari undangan tersebut mas

**Comment by karuniawanekasakti** [comment]
> Kemungkinan besar ada pada frontend dari undangan tersebut mas

dibagian mana nya ya mas? mohon bantuannya mas soalnya kemarin udah lancar nampilin commentnya, sekarang malah error bearer token kosong

_Update sekarang error signature verification failed_

![image](https://github.com/dewanakl/undangan-api/assets/74005888/05f2928f-f262-485c-a977-0faf82681623)

**Comment by karuniawanekasakti** [comment]
> > Kemungkinan besar ada pada frontend dari undangan tersebut mas
> 
> dibagian mana nya ya mas? mohon bantuannya mas soalnya kemarin udah lancar nampilin commentnya, sekarang malah error bearer token kosong
> 
> _Update sekarang error signature verification failed_
> 
> ![image](https://private-user-images.githubusercontent.com/74005888/291848044-05f2928f-f262-485c-a977-0faf82681623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjUzNDIsIm5iZiI6MTcwMzA2NTA0MiwicGF0aCI6Ii83NDAwNTg4OC8yOTE4NDgwNDQtMDVmMjkyOGYtZjI2Mi00ODVjLWE5NzctMGZhZjgyNjgxNjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZDk0MzZiOGFkYjliY2IwZTA3ZGQ2NGZkNWUyOTYwZWJjMTY1MTRlMTBjMzkwNjMyMDNhMmQ0OWY2YzcwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-RtZ6DCTwF8p9-hroAJUqhb0r84JiWGCUxl0MjLExc)

kalau saya pakai API punya mas nya malah bisa, tapi ketika pakai API yang saya deploy malah ga bisa juga mas

**Comment by dewanakl** [comment]
Coba mas, clear tokennya yang ada pada localstorage

**Comment by dewanakl** [comment]
Apakah sudah solve mas?
