### ISSUE TITLE
Izin tanya mas

### ISSUE THREAD

**Issue by eabdalmufid** [dewanakl/undangan-api#9]
![IMG-20240206-WA0000](https://github.com/dewanakl/undangan-api/assets/110360966/4da63825-5423-42ba-b1b2-3f4fb37627a6)

Kenapa ini ya mas

**Comment by dewanakl** [comment]
Driver database pada vps untuk php belum ada mas
masnya bisa install terlebih dahulu, mysql atau pgsql tergantung database yang dipake sama masnya, terima kasih

**Comment by eabdalmufid** [comment]
> Driver database pada vps untuk php belum ada mas masnya bisa install terlebih dahulu, mysql atau pgsql tergantung database yang dipake sama masnya, terima kasih

Sudah mas, masih sama

**Comment by dewanakl** [comment]
Pada env pastikan ada file .env dan pastikan juga file cache pada folder env juga kosong mas

**Comment by eabdalmufid** [comment]
> Pada env pastikan ada file .env dan pastikan juga file cache pada folder env juga kosong mas

![Screenshot_2024-02-06-12-40-39-819_com alphainventor filemanager](https://github.com/dewanakl/undangan-api/assets/110360966/eb5637c4-b02d-4eb6-8a9d-a4a8d7db0131)
Sudah mengikuti yang di YouTube mas

**Comment by dewanakl** [comment]
Coba mas, bikin file PHP dengan isi phpinfo() untuk melihat driver yang
terinstal pada PHP nya

Pada Sel, 6 Feb 2024 12.41, Afidev ***@***.***> menulis:
